# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_MainWindow.ui',
# licensing of 'Ui_MainWindow.ui' applies.
#
# Created: Thu Jan 31 09:03:34 2019
#      by: pyside2-uic  running on PySide2 5.12.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(852, 592)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../green_orca.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(10, 0))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEditIpRange = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditIpRange.sizePolicy().hasHeightForWidth())
        self.lineEditIpRange.setSizePolicy(sizePolicy)
        self.lineEditIpRange.setObjectName("lineEditIpRange")
        self.horizontalLayout_2.addWidget(self.lineEditIpRange)
        self.verticalLayout_2.addWidget(self.widget)
        self.btnDetectClient = QtWidgets.QPushButton(self.centralwidget)
        self.btnDetectClient.setObjectName("btnDetectClient")
        self.verticalLayout_2.addWidget(self.btnDetectClient)
        self.btnSelectAllClients = QtWidgets.QPushButton(self.centralwidget)
        self.btnSelectAllClients.setObjectName("btnSelectAllClients")
        self.verticalLayout_2.addWidget(self.btnSelectAllClients)
        self.btnSelectExam = QtWidgets.QPushButton(self.centralwidget)
        self.btnSelectExam.setEnabled(False)
        self.btnSelectExam.setObjectName("btnSelectExam")
        self.verticalLayout_2.addWidget(self.btnSelectExam)
        self.btnPrepareExam = QtWidgets.QPushButton(self.centralwidget)
        self.btnPrepareExam.setEnabled(False)
        self.btnPrepareExam.setAutoFillBackground(False)
        self.btnPrepareExam.setObjectName("btnPrepareExam")
        self.verticalLayout_2.addWidget(self.btnPrepareExam)
        self.checkBoxBlockUsb = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxBlockUsb.setChecked(True)
        self.checkBoxBlockUsb.setObjectName("checkBoxBlockUsb")
        self.verticalLayout_2.addWidget(self.checkBoxBlockUsb)
        self.checkBoxBlockWebAccess = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxBlockWebAccess.setChecked(True)
        self.checkBoxBlockWebAccess.setObjectName("checkBoxBlockWebAccess")
        self.verticalLayout_2.addWidget(self.checkBoxBlockWebAccess)
        self.btnGetExams = QtWidgets.QPushButton(self.centralwidget)
        self.btnGetExams.setEnabled(False)
        self.btnGetExams.setObjectName("btnGetExams")
        self.verticalLayout_2.addWidget(self.btnGetExams)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.btnSendMessage = QtWidgets.QPushButton(self.centralwidget)
        self.btnSendMessage.setObjectName("btnSendMessage")
        self.verticalLayout_2.addWidget(self.btnSendMessage)
        self.btnResetAllClients = QtWidgets.QPushButton(self.centralwidget)
        self.btnResetAllClients.setObjectName("btnResetAllClients")
        self.verticalLayout_2.addWidget(self.btnResetAllClients)
        self.btnUnselectAllClients = QtWidgets.QPushButton(self.centralwidget)
        self.btnUnselectAllClients.setObjectName("btnUnselectAllClients")
        self.verticalLayout_2.addWidget(self.btnUnselectAllClients)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_pcs = QtWidgets.QWidget()
        self.tab_pcs.setObjectName("tab_pcs")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_pcs)
        self.verticalLayout.setObjectName("verticalLayout")
        self.clientFrame = QtWidgets.QFrame(self.tab_pcs)
        self.clientFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.clientFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.clientFrame.setObjectName("clientFrame")
        self.verticalLayout.addWidget(self.clientFrame)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalFrame = QtWidgets.QFrame(self.tab_pcs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame.sizePolicy().hasHeightForWidth())
        self.horizontalFrame.setSizePolicy(sizePolicy)
        self.horizontalFrame.setObjectName("horizontalFrame")
        self._2 = QtWidgets.QGridLayout(self.horizontalFrame)
        self._2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self._2.setContentsMargins(-1, 0, -1, -1)
        self._2.setObjectName("_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self._2.addItem(spacerItem2, 0, 0, 1, 1)
        self._2.setColumnStretch(0, 1)
        self.verticalLayout.addWidget(self.horizontalFrame)
        self.tabWidget.addTab(self.tab_pcs, "")
        self.tab_lb = QtWidgets.QWidget()
        self.tab_lb.setObjectName("tab_lb")
        self.textEdit = QtWidgets.QTextEdit(self.tab_lb)
        self.textEdit.setGeometry(QtCore.QRect(10, 10, 581, 431))
        self.textEdit.setObjectName("textEdit")
        self.tabWidget.addTab(self.tab_lb, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 1, 1, 1)
        self.labelProgress = QtWidgets.QLabel(self.centralwidget)
        self.labelProgress.setObjectName("labelProgress")
        self.gridLayout_2.addWidget(self.labelProgress, 2, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setEnabled(False)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_2.addWidget(self.progressBar, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 852, 23))
        self.menubar.setObjectName("menubar")
        self.menuKonfiguration = QtWidgets.QMenu(self.menubar)
        self.menuKonfiguration.setObjectName("menuKonfiguration")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusbar.sizePolicy().hasHeightForWidth())
        self.statusbar.setSizePolicy(sizePolicy)
        self.statusbar.setMinimumSize(QtCore.QSize(100, 20))
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionBearbeiten = QtWidgets.QAction(MainWindow)
        self.actionBearbeiten.setObjectName("actionBearbeiten")
        self.menuKonfiguration.addAction(self.actionBearbeiten)
        self.menubar.addAction(self.menuKonfiguration.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "IP-Bereich: ", None, -1))
        self.lineEditIpRange.setText(QtWidgets.QApplication.translate("MainWindow", "192.168.0.*", None, -1))
        self.btnDetectClient.setText(QtWidgets.QApplication.translate("MainWindow", "Clients erkennen", None, -1))
        self.btnSelectAllClients.setText(QtWidgets.QApplication.translate("MainWindow", "Alle Clients auswählen", None, -1))
        self.btnSelectExam.setText(QtWidgets.QApplication.translate("MainWindow", "Prüfung auswählen", None, -1))
        self.btnPrepareExam.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Achtung: bereits vorhandene Daten werden überschrieben", None, -1))
        self.btnPrepareExam.setText(QtWidgets.QApplication.translate("MainWindow", "Prüfung einspielen", None, -1))
        self.checkBoxBlockUsb.setText(QtWidgets.QApplication.translate("MainWindow", "USB blockieren", None, -1))
        self.checkBoxBlockWebAccess.setText(QtWidgets.QApplication.translate("MainWindow", "Web blockieren", None, -1))
        self.btnGetExams.setText(QtWidgets.QApplication.translate("MainWindow", "Prüfungsdaten abholen", None, -1))
        self.btnSendMessage.setToolTip(QtWidgets.QApplication.translate("MainWindow", "sendet Nachricht an alle ausgewählten Clients.", None, -1))
        self.btnSendMessage.setText(QtWidgets.QApplication.translate("MainWindow", "Benutzer benachrichtigen", None, -1))
        self.btnResetAllClients.setText(QtWidgets.QApplication.translate("MainWindow", "Alle Clients zurücksetzen", None, -1))
        self.btnUnselectAllClients.setText(QtWidgets.QApplication.translate("MainWindow", "Alle Clients deaktivieren", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_pcs), QtWidgets.QApplication.translate("MainWindow", "Client - PCs", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_lb), QtWidgets.QApplication.translate("MainWindow", "LB", None, -1))
        self.labelProgress.setText(QtWidgets.QApplication.translate("MainWindow", "Fortschritt:", None, -1))
        self.menuKonfiguration.setTitle(QtWidgets.QApplication.translate("MainWindow", "&Konfiguration", None, -1))
        self.actionBearbeiten.setText(QtWidgets.QApplication.translate("MainWindow", "&Bearbeiten", None, -1))

