# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/Ui_MainWindow.ui',
# licensing of 'ui/Ui_MainWindow.ui' applies.
#
# Created: Sat May 11 21:18:47 2019
#      by: pyside2-uic  running on PySide2 5.12.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1115, 587)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../green_orca.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(10, 0))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEditIpRange = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditIpRange.sizePolicy().hasHeightForWidth())
        self.lineEditIpRange.setSizePolicy(sizePolicy)
        self.lineEditIpRange.setObjectName("lineEditIpRange")
        self.horizontalLayout_2.addWidget(self.lineEditIpRange)
        self.verticalLayout_2.addWidget(self.widget)
        self.btnDetectClient = QtWidgets.QPushButton(self.centralwidget)
        self.btnDetectClient.setObjectName("btnDetectClient")
        self.verticalLayout_2.addWidget(self.btnDetectClient)
        self.btnSelectExam = QtWidgets.QPushButton(self.centralwidget)
        self.btnSelectExam.setEnabled(False)
        self.btnSelectExam.setObjectName("btnSelectExam")
        self.verticalLayout_2.addWidget(self.btnSelectExam)
        self.btnPrepareExam = QtWidgets.QPushButton(self.centralwidget)
        self.btnPrepareExam.setEnabled(False)
        self.btnPrepareExam.setAutoFillBackground(False)
        self.btnPrepareExam.setObjectName("btnPrepareExam")
        self.verticalLayout_2.addWidget(self.btnPrepareExam)
        self.checkBoxWipeHomedir = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxWipeHomedir.setToolTip("")
        self.checkBoxWipeHomedir.setChecked(True)
        self.checkBoxWipeHomedir.setObjectName("checkBoxWipeHomedir")
        self.verticalLayout_2.addWidget(self.checkBoxWipeHomedir)
        self.checkBoxBlockUsb = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxBlockUsb.setChecked(True)
        self.checkBoxBlockUsb.setObjectName("checkBoxBlockUsb")
        self.verticalLayout_2.addWidget(self.checkBoxBlockUsb)
        self.checkBoxBlockWebAccess = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxBlockWebAccess.setChecked(True)
        self.checkBoxBlockWebAccess.setObjectName("checkBoxBlockWebAccess")
        self.verticalLayout_2.addWidget(self.checkBoxBlockWebAccess)
        self.btnGetExams = QtWidgets.QPushButton(self.centralwidget)
        self.btnGetExams.setEnabled(False)
        self.btnGetExams.setObjectName("btnGetExams")
        self.verticalLayout_2.addWidget(self.btnGetExams)
        self.btnSaveExamLog = QtWidgets.QPushButton(self.centralwidget)
        self.btnSaveExamLog.setObjectName("btnSaveExamLog")
        self.verticalLayout_2.addWidget(self.btnSaveExamLog)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.tabs.setObjectName("tabs")
        self.tab_pcs = QtWidgets.QWidget()
        self.tab_pcs.setObjectName("tab_pcs")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_pcs)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.tab_pcs)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnSelectAllClients = QtWidgets.QPushButton(self.frame)
        self.btnSelectAllClients.setStyleSheet("text-align:center")
        self.btnSelectAllClients.setObjectName("btnSelectAllClients")
        self.horizontalLayout.addWidget(self.btnSelectAllClients)
        self.btnUnselectClients = QtWidgets.QPushButton(self.frame)
        self.btnUnselectClients.setObjectName("btnUnselectClients")
        self.horizontalLayout.addWidget(self.btnUnselectClients)
        self.verticalLayout.addWidget(self.frame)
        self.clientFrame = QtWidgets.QFrame(self.tab_pcs)
        self.clientFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.clientFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.clientFrame.setObjectName("clientFrame")
        self.verticalLayout.addWidget(self.clientFrame)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalFrame = QtWidgets.QFrame(self.tab_pcs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame.sizePolicy().hasHeightForWidth())
        self.horizontalFrame.setSizePolicy(sizePolicy)
        self.horizontalFrame.setObjectName("horizontalFrame")
        self._2 = QtWidgets.QGridLayout(self.horizontalFrame)
        self._2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self._2.setContentsMargins(-1, 0, -1, -1)
        self._2.setObjectName("_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self._2.addItem(spacerItem2, 0, 0, 1, 1)
        self._2.setColumnStretch(0, 1)
        self.verticalLayout.addWidget(self.horizontalFrame)
        self.tabs.addTab(self.tab_pcs, "")
        self.tab_candidates = QtWidgets.QWidget()
        self.tab_candidates.setObjectName("tab_candidates")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_candidates)
        self.gridLayout.setObjectName("gridLayout")
        self.btnApplyCandidateNames = QtWidgets.QPushButton(self.tab_candidates)
        self.btnApplyCandidateNames.setObjectName("btnApplyCandidateNames")
        self.gridLayout.addWidget(self.btnApplyCandidateNames, 1, 0, 1, 1)
        self.checkBox_OverwriteExisitingNames = QtWidgets.QCheckBox(self.tab_candidates)
        self.checkBox_OverwriteExisitingNames.setObjectName("checkBox_OverwriteExisitingNames")
        self.gridLayout.addWidget(self.checkBox_OverwriteExisitingNames, 1, 1, 1, 1)
        self.textEditCandidates = QtWidgets.QTextEdit(self.tab_candidates)
        self.textEditCandidates.setAcceptRichText(False)
        self.textEditCandidates.setObjectName("textEditCandidates")
        self.gridLayout.addWidget(self.textEditCandidates, 0, 0, 1, 2)
        self.tabs.addTab(self.tab_candidates, "")
        self.tab_log = QtWidgets.QWidget()
        self.tab_log.setObjectName("tab_log")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_log)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.textEditLog = QtWidgets.QTextEdit(self.tab_log)
        self.textEditLog.setObjectName("textEditLog")
        self.gridLayout_3.addWidget(self.textEditLog, 0, 0, 1, 1)
        self.tabs.addTab(self.tab_log, "")
        self.gridLayout_2.addWidget(self.tabs, 0, 1, 1, 1)
        self.labelProgress = QtWidgets.QLabel(self.centralwidget)
        self.labelProgress.setObjectName("labelProgress")
        self.gridLayout_2.addWidget(self.labelProgress, 2, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setEnabled(False)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_2.addWidget(self.progressBar, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1115, 23))
        self.menubar.setObjectName("menubar")
        self.menuKonfiguration = QtWidgets.QMenu(self.menubar)
        self.menuKonfiguration.setObjectName("menuKonfiguration")
        self.menuBatch_Operationen = QtWidgets.QMenu(self.menubar)
        self.menuBatch_Operationen.setObjectName("menuBatch_Operationen")
        self.menuHilfe = QtWidgets.QMenu(self.menubar)
        self.menuHilfe.setObjectName("menuHilfe")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusbar.sizePolicy().hasHeightForWidth())
        self.statusbar.setSizePolicy(sizePolicy)
        self.statusbar.setMinimumSize(QtCore.QSize(100, 20))
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionBearbeiten = QtWidgets.QAction(MainWindow)
        self.actionBearbeiten.setObjectName("actionBearbeiten")
        self.actionAlle_Clients_zur_cksetzen = QtWidgets.QAction(MainWindow)
        self.actionAlle_Clients_zur_cksetzen.setObjectName("actionAlle_Clients_zur_cksetzen")
        self.actionAlle_Clients_deaktivieren = QtWidgets.QAction(MainWindow)
        self.actionAlle_Clients_deaktivieren.setObjectName("actionAlle_Clients_deaktivieren")
        self.actionAlle_Clients_rebooten = QtWidgets.QAction(MainWindow)
        self.actionAlle_Clients_rebooten.setObjectName("actionAlle_Clients_rebooten")
        self.actionAlle_Clients_herunterfahren = QtWidgets.QAction(MainWindow)
        self.actionAlle_Clients_herunterfahren.setObjectName("actionAlle_Clients_herunterfahren")
        self.actionAlle_Benutzer_benachrichtigen = QtWidgets.QAction(MainWindow)
        self.actionAlle_Benutzer_benachrichtigen.setObjectName("actionAlle_Benutzer_benachrichtigen")
        self.actionOnlineHelp = QtWidgets.QAction(MainWindow)
        self.actionOnlineHelp.setObjectName("actionOnlineHelp")
        self.menuKonfiguration.addAction(self.actionBearbeiten)
        self.menuBatch_Operationen.addAction(self.actionAlle_Clients_zur_cksetzen)
        self.menuBatch_Operationen.addAction(self.actionAlle_Clients_rebooten)
        self.menuBatch_Operationen.addAction(self.actionAlle_Clients_herunterfahren)
        self.menuBatch_Operationen.addSeparator()
        self.menuBatch_Operationen.addAction(self.actionAlle_Benutzer_benachrichtigen)
        self.menuHilfe.addAction(self.actionOnlineHelp)
        self.menubar.addAction(self.menuKonfiguration.menuAction())
        self.menubar.addAction(self.menuBatch_Operationen.menuAction())
        self.menubar.addAction(self.menuHilfe.menuAction())

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "IP-Bereich: ", None, -1))
        self.lineEditIpRange.setText(QtWidgets.QApplication.translate("MainWindow", "192.168.0.*", None, -1))
        self.btnDetectClient.setText(QtWidgets.QApplication.translate("MainWindow", "Clients erkennen", None, -1))
        self.btnSelectExam.setText(QtWidgets.QApplication.translate("MainWindow", "Prüfung auswählen", None, -1))
        self.btnPrepareExam.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Achtung: bereits vorhandene Daten werden überschrieben", None, -1))
        self.btnPrepareExam.setText(QtWidgets.QApplication.translate("MainWindow", "Prüfung einspielen", None, -1))
        self.checkBoxWipeHomedir.setText(QtWidgets.QApplication.translate("MainWindow", "HOME-Verzeichnis leeren", None, -1))
        self.checkBoxBlockUsb.setText(QtWidgets.QApplication.translate("MainWindow", "USB blockieren", None, -1))
        self.checkBoxBlockWebAccess.setText(QtWidgets.QApplication.translate("MainWindow", "Web blockieren", None, -1))
        self.btnGetExams.setText(QtWidgets.QApplication.translate("MainWindow", "Prüfungsdaten abholen", None, -1))
        self.btnSaveExamLog.setText(QtWidgets.QApplication.translate("MainWindow", "Prüfungslog speichern", None, -1))
        self.btnSelectAllClients.setText(QtWidgets.QApplication.translate("MainWindow", "Alle Client-PCs auswählen", None, -1))
        self.btnUnselectClients.setText(QtWidgets.QApplication.translate("MainWindow", "Alle Client-PCs abwählen", None, -1))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_pcs), QtWidgets.QApplication.translate("MainWindow", "Client - PCs", None, -1))
        self.btnApplyCandidateNames.setText(QtWidgets.QApplication.translate("MainWindow", "Kandidatennamen zuweisen", None, -1))
        self.checkBox_OverwriteExisitingNames.setText(QtWidgets.QApplication.translate("MainWindow", "existierende Namen überschreiben", None, -1))
        self.textEditCandidates.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Copy / paste Kandidatennamen aus Excel (pro Zeile ein Name)", None, -1))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_candidates), QtWidgets.QApplication.translate("MainWindow", "Kandidaten", None, -1))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_log), QtWidgets.QApplication.translate("MainWindow", "Log", None, -1))
        self.labelProgress.setText(QtWidgets.QApplication.translate("MainWindow", "Fortschritt:", None, -1))
        self.menuKonfiguration.setTitle(QtWidgets.QApplication.translate("MainWindow", "&Konfiguration", None, -1))
        self.menuBatch_Operationen.setTitle(QtWidgets.QApplication.translate("MainWindow", "&Batch-Operationen", None, -1))
        self.menuHilfe.setTitle(QtWidgets.QApplication.translate("MainWindow", "Hi&lfe", None, -1))
        self.actionBearbeiten.setText(QtWidgets.QApplication.translate("MainWindow", "&Bearbeiten", None, -1))
        self.actionAlle_Clients_zur_cksetzen.setText(QtWidgets.QApplication.translate("MainWindow", "&Alle Clients zurücksetzen", None, -1))
        self.actionAlle_Clients_deaktivieren.setText(QtWidgets.QApplication.translate("MainWindow", "Alle &Clients: Auswahl aufheben", None, -1))
        self.actionAlle_Clients_rebooten.setText(QtWidgets.QApplication.translate("MainWindow", "Alle Clients &rebooten", None, -1))
        self.actionAlle_Clients_herunterfahren.setText(QtWidgets.QApplication.translate("MainWindow", "Alle Clients &herunterfahren", None, -1))
        self.actionAlle_Benutzer_benachrichtigen.setText(QtWidgets.QApplication.translate("MainWindow", "Alle &Benutzer benachrichtigen", None, -1))
        self.actionOnlineHelp.setText(QtWidgets.QApplication.translate("MainWindow", "&Online-Hilfe öffnen", None, -1))

